import { Urbanist } from "next/font/google"
import "./globals.css"
import Nav from "@/components/nav/Nav"
import Footer from "@/components/Footer"
import { ClerkProvider } from '@clerk/nextjs'

const urbanist = Urbanist({ subsets: ["latin"] })
export const metadata = {
  title: "Ecommerce Store",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={urbanist.className}>
        <div className="mx-auto max-w-7xl">
          <Nav />
          <div className="p-4 sm:p-6 lg:p-8 ">
          {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
    </ClerkProvider>
  )
}
